name: iosApp
options:
  bundleIdPrefix: com.a2ui
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "1540"

settings:
  base:
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.a2ui.iosApp
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-framework"
          - "ComposeApp"
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    dependencies: []
